### ISSUE TITLE
Questions about the evaluation of SparklesChat versus Minigpt-4

### ISSUE THREAD

**Issue by valorix25** [HYPJUDY/Sparkles#3]
To the best of my knowledge, MiniGPT-4 can only process a single image at a time. Could you please explain how you managed to get it to handle multiple images simultaneously?

> The Minigpt-4 url: https://huggingface.co/spaces/Vision-CAIR/minigpt4

**Comment by HYPJUDY** [comment]
Thank you for your query regarding the handling of multiple images in MiniGPT-4. 

The adaptation of MiniGPT-4 to handle multiple images simultaneously mainly involves embedding these images within the text context. For the **modeling** implementation, below are the original `forward_minigpt4` function used by MiniGPT-4 and the enhanced `forward` function for multiple images used by our SparklesChat.

https://github.com/HYPJUDY/Sparkles/blob/913424a4ded9373705c772798e25d3c1a17e7616/sparkles/models/sparkleschat.py#L175-L261

The `forward_minigpt4` function processes a single image from the samples. It creates embeddings for the image, combines them with text embeddings, and feeds the concatenated embeddings as `inputs_embeds` to the model.
The `forward` function enhances the capability to process multiple images. For each input, the function identifies the positions of image tokens (`self.media_token_id`) and embeds the corresponding images into the text sequence.

For the implementation of preparing image-text interleaved multimodal **data** with embeded image tokens for SparklesDialogue, please refer to the `MultimodalDialogueDataset` class in https://github.com/HYPJUDY/Sparkles/blob/913424a4ded9373705c772798e25d3c1a17e7616/sparkles/datasets/datasets/multimodal_dialogue_dataset.py#L49
