### ISSUE TITLE
Slow Download Speed

### ISSUE THREAD

**Issue by Hambaobao** [HYPJUDY/Sparkles#4]
Dear author, thank you very much for your outstanding work. I would like to train our model using the Sparkles dataset, but the file download speed from OneDrive is very slow because the files you uploaded are scattered. If you could upload a .zip compressed file, our download speed would be much faster.

**Comment by HYPJUDY** [comment]
Thank you for your kind words and your suggestion!
I have now compressed the folders containing the scattered images into .zip files and located them in the same directory as the original folders. Here's how the OneDrive directory now looks:

```
Sparkles
├── data
│   ├── SparklesDialogueCC
│   ├── SparklesDialogueCC.zip
│   ├── SparklesDialogueVG
│   ├── SparklesDialogueVG.zip
...
├── evaluation
├── evaluation.zip
...
```

If there are any other specific folders you need compressed to improve the experience with the dataset, please feel free to let me know.

**Comment by Hambaobao** [comment]
Awesome!

**Comment by Mac0q** [comment]
`SparklesDialogueCC.zip` appears to be missing from the `data` folder.
